import Head from "next/head";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Create t3e App</title>
        <meta name="description" content="Generated by create-t3e-app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={inter.className}>
        <div>
          <h1>Create t3e App</h1>
          <p>
            You can start by editing
            <code> src/pages/index.ts</code>
          </p>
        </div>
      </main>
    </>
  );
}
